# Generated by Django 4.1.2 on 2022-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interest_per_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('first_keyword', models.TextField()),
                ('second_keyword', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
