# Generated by Django 4.1.2 on 2022-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0002_interest_per_region_first_keyword_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest_per_region',
            name='first_keyword_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interest_per_region',
            name='second_keyword_data',
            field=models.TextField(),
        ),
    ]
