# Generated by Django 4.1.2 on 2022-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0003_alter_interest_per_region_first_keyword_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('keyword', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
