# Generated by Django 4.1.2 on 2022-10-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0004_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='data',
            field=models.JSONField(),
        ),
    ]
