# Generated by Django 4.1.2 on 2022-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0005_alter_historical_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='data',
            field=models.TextField(),
        ),
    ]
