# Generated by Django 3.2.16 on 2022-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0006_alter_historical_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='data',
            field=models.JSONField(),
        ),
    ]
